# Generated by Django 4.1.5 on 2023-12-27 04:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tag_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagsmodel',
            name='tag_id',
        ),
        migrations.RemoveField(
            model_name='vm',
            name='vm_id',
        ),
        migrations.AlterField(
            model_name='tagsmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vm',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
