# Generated by Django 4.1.5 on 2023-12-27 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag_api', '0002_remove_tagsmodel_tag_id_remove_vm_vm_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagsmodel',
            old_name='id',
            new_name='tag_id',
        ),
        migrations.RenameField(
            model_name='vm',
            old_name='id',
            new_name='vm_id',
        ),
    ]
