# Generated by Django 4.1.5 on 2023-12-27 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag_api', '0003_rename_id_tagsmodel_tag_id_rename_id_vm_vm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagsmodel',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
