# Generated by Django 4.1.5 on 2023-12-27 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag_api', '0004_tagsmodel_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'user',
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='tagsmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tag_api.userprofile'),
        ),
    ]
