# Generated by Django 4.1.5 on 2023-12-27 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag_api', '0006_rename_created_by_tagsmodel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsmodel',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tag_api.userprofile'),
        ),
    ]
