# Generated by Django 4.1.5 on 2023-12-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag_api', '0008_userprofile_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_admin',
        ),
    ]
