# Generated by Django 4.1.5 on 2023-12-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_api', '0009_remove_userprofile_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsmodel',
            name='tag_name',
            field=models.CharField(max_length=255, verbose_name='tag_name'),
        ),
    ]
