# Generated by Django 4.1.5 on 2023-12-28 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag_api', '0012_alter_tagsmodel_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsmodel',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='tag_api.userprofile'),
        ),
    ]
