# Generated by Django 4.1.5 on 2023-12-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag_api', '0013_alter_tagsmodel_user_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagsmodel',
            unique_together=set(),
        ),
    ]
