# Generated by Django 4.1.5 on 2023-12-29 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag_api', '0015_alter_tagsmodel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagsmodel',
            unique_together=set(),
        ),
    ]
